version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: circleci/node:16
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/TrizaCorporation/StatusSoftware/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  publish-version:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - publish-version