version: 2.1
jobs:
  publish-version:
    docker: 
      - image: electronuserland/builder:wine
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/TrizaCorporation/StatusSoftware/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
      - image: node:19
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/TrizaCorporation/StatusSoftware/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run: npm install
      - run: npm run bap

workflows:
  manage-version:
    jobs:
      - publish-version
