version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  publish-win:
    docker: 
      - image: electronuserland/builder:wine
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/TrizaCorporation/StatusSoftware/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run: npm install
      - run: npm run build-publish:win
  publish-mac: 
      macos:
        xcode: 14.2.0
      steps:
        - checkout
        - node/install:
            node-version: "16.16.0"
        - run: npm install
        - run: npm run build-publish:mac
  publish-linux:
      machine:
        image: ubuntu-2004:2023.04.2
      steps:
        - checkout
        - node/install:
            node-version: "16.16.0"
        - run: npm install
        - run: npm run build-publish:linux
workflows:
  manage-version:
      jobs:
        - publish-win
        - publish-mac
