version: 2.1
jobs:
  publish-win:
    docker: 
      - image: electronuserland/builder:wine
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/TrizaCorporation/StatusSoftware/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run: npm install
      - run: npm run build-publish:win
  publish-mac: 
      macos:
        xcode: 11.0.0
      steps:
        - node/install:
            node-version: "13.11.0"
        - run: npm install
        - run: npm run build-publish:mac
workflows:
  manage-version:
      jobs:
        - publish-win
        - publish-mac
